-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  action character varying NOT NULL,
  admin_user_id character varying,
  details jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.automation_executions (
  execution_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  automation_id uuid NOT NULL,
  transaction_id uuid,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['success'::character varying, 'failed'::character varying, 'pending'::character varying]::text[])),
  error_message text,
  executed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT automation_executions_pkey PRIMARY KEY (execution_id),
  CONSTRAINT automation_executions_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES public.automations(automation_id),
  CONSTRAINT automation_executions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id)
);
CREATE TABLE public.automations (
  automation_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  name character varying NOT NULL,
  token character varying NOT NULL,
  action_type character varying NOT NULL CHECK (action_type::text = ANY (ARRAY['convert'::character varying, 'transfer'::character varying, 'split'::character varying, 'swap'::character varying]::text[])),
  condition_type character varying NOT NULL,
  condition_value numeric NOT NULL,
  action_description text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT automations_pkey PRIMARY KEY (automation_id),
  CONSTRAINT automations_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  company character varying,
  billing_address jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.fee_collections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chain_id integer NOT NULL,
  tx_hash character varying NOT NULL,
  block_number bigint NOT NULL,
  log_index integer NOT NULL,
  token character varying NOT NULL,
  fee_amount character varying NOT NULL,
  fee_collector character varying NOT NULL,
  occurred_at timestamp with time zone DEFAULT now(),
  tx_event_id uuid,
  CONSTRAINT fee_collections_pkey PRIMARY KEY (id),
  CONSTRAINT fee_collections_tx_event_id_fkey FOREIGN KEY (tx_event_id) REFERENCES public.tx_events(id)
);
CREATE TABLE public.indexer_checkpoints (
  chain_id integer NOT NULL,
  last_block bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT indexer_checkpoints_pkey PRIMARY KEY (chain_id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  terminal_id uuid,
  chain_id integer NOT NULL,
  token character varying NOT NULL,
  amount character varying NOT NULL,
  fee_amount character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'detected'::character varying::text, 'confirmed'::character varying::text, 'paid'::character varying::text, 'expired'::character varying::text, 'cancelled'::character varying::text])),
  description text,
  metadata jsonb,
  payment_uri text,
  expires_at timestamp with time zone,
  tx_hash character varying,
  payer_address character varying,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  currency character varying DEFAULT 'USD'::character varying,
  transaction_id uuid,
  receiver_address character varying,
  deployed boolean DEFAULT false,
  amount_paid character varying,
  token_address character varying,
  payment_tx character varying,
  deploy_tx character varying,
  error_message text,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT invoices_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id),
  CONSTRAINT invoices_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id)
);
CREATE TABLE public.locations (
  location_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  name character varying NOT NULL,
  address text,
  timezone character varying DEFAULT 'UTC'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (location_id),
  CONSTRAINT locations_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.merchant_chain_addresses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  chain_id integer NOT NULL,
  payout_address character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT merchant_chain_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT merchant_chain_addresses_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.merchant_documents (
  document_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  document_type character varying NOT NULL CHECK (document_type::text = ANY (ARRAY['merchant_agreement'::character varying::text, 'crypto_disclosure'::character varying::text, 'privacy_policy'::character varying::text, 'terms_of_service'::character varying::text, 'kyc_document'::character varying::text, 'compliance_certificate'::character varying::text, 'other'::character varying::text])),
  document_title character varying NOT NULL,
  document_description text,
  file_url text NOT NULL,
  file_size integer,
  mime_type character varying DEFAULT 'application/pdf'::character varying CHECK (mime_type::text = ANY (ARRAY['application/pdf'::character varying::text, 'application/msword'::character varying::text, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'::character varying::text, 'text/plain'::character varying::text])),
  version character varying NOT NULL,
  signed_date timestamp with time zone,
  effective_date timestamp with time zone,
  signed_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT merchant_documents_pkey PRIMARY KEY (document_id),
  CONSTRAINT merchant_documents_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT merchant_documents_signed_by_user_id_fkey FOREIGN KEY (signed_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.merchant_wallets (
  wallet_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT merchant_wallets_pkey PRIMARY KEY (wallet_id),
  CONSTRAINT merchant_wallets_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.merchants (
  merchant_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  logo_url character varying,
  website character varying,
  industry character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying]::text[])),
  business_phone character varying,
  business_email character varying,
  virtual_terminal_enabled boolean DEFAULT true,
  payout_address character varying,
  merchant_agreement_url text,
  crypto_disclosure_url text,
  business_street character varying,
  business_city character varying,
  business_state character varying,
  business_country character varying,
  business_postal_code character varying,
  CONSTRAINT merchants_pkey PRIMARY KEY (merchant_id)
);
CREATE TABLE public.okuru_alerts (
  alert_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid,
  alert_type character varying NOT NULL,
  severity character varying DEFAULT 'medium'::character varying CHECK (severity::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  title character varying NOT NULL,
  message text NOT NULL,
  alert_data jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'acknowledged'::character varying, 'resolved'::character varying, 'dismissed'::character varying]::text[])),
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT okuru_alerts_pkey PRIMARY KEY (alert_id),
  CONSTRAINT okuru_alerts_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT okuru_alerts_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.okuru_company_settings (
  setting_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  setting_key character varying NOT NULL UNIQUE,
  setting_value text NOT NULL,
  setting_type character varying DEFAULT 'string'::character varying CHECK (setting_type::text = ANY (ARRAY['string'::character varying, 'number'::character varying, 'boolean'::character varying, 'json'::character varying]::text[])),
  description text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT okuru_company_settings_pkey PRIMARY KEY (setting_id)
);
CREATE TABLE public.okuru_fee_collections (
  collection_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transaction_id uuid NOT NULL,
  merchant_id uuid NOT NULL,
  fee_rate numeric NOT NULL,
  gross_amount_fiat numeric NOT NULL,
  fee_amount_fiat numeric NOT NULL,
  fee_amount_crypto numeric NOT NULL,
  net_amount_fiat numeric NOT NULL,
  net_amount_crypto numeric NOT NULL,
  collection_method character varying DEFAULT 'automatic'::character varying,
  collection_status character varying DEFAULT 'pending'::character varying CHECK (collection_status::text = ANY (ARRAY['pending'::character varying, 'collected'::character varying, 'failed'::character varying, 'disputed'::character varying]::text[])),
  collection_tx_hash character varying,
  fiat_currency character varying NOT NULL,
  crypto_currency character varying NOT NULL,
  blockchain character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  collected_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT okuru_fee_collections_pkey PRIMARY KEY (collection_id),
  CONSTRAINT okuru_fee_collections_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id),
  CONSTRAINT okuru_fee_collections_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.okuru_global_analytics (
  analytics_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  period_date date NOT NULL,
  period_type character varying DEFAULT 'daily'::character varying CHECK (period_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying]::text[])),
  total_merchants integer DEFAULT 0,
  active_merchants integer DEFAULT 0,
  new_merchants integer DEFAULT 0,
  total_transactions integer DEFAULT 0,
  successful_transactions integer DEFAULT 0,
  failed_transactions integer DEFAULT 0,
  gross_volume_fiat numeric DEFAULT 0,
  net_volume_fiat numeric DEFAULT 0,
  total_okuru_fees_fiat numeric DEFAULT 0,
  total_okuru_fees_crypto jsonb DEFAULT '{}'::jsonb,
  total_terminals integer DEFAULT 0,
  active_terminals integer DEFAULT 0,
  total_locations integer DEFAULT 0,
  supported_cryptos jsonb DEFAULT '[]'::jsonb,
  crypto_volumes jsonb DEFAULT '{}'::jsonb,
  top_crypto_by_volume character varying,
  total_staff integer DEFAULT 0,
  active_staff integer DEFAULT 0,
  total_automations integer DEFAULT 0,
  active_automations integer DEFAULT 0,
  automation_executions integer DEFAULT 0,
  merchant_growth_rate numeric DEFAULT 0,
  volume_growth_rate numeric DEFAULT 0,
  revenue_growth_rate numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT okuru_global_analytics_pkey PRIMARY KEY (analytics_id)
);
CREATE TABLE public.okuru_merchant_analytics (
  analytics_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  period_date date NOT NULL,
  period_type character varying DEFAULT 'daily'::character varying CHECK (period_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying]::text[])),
  total_transactions integer DEFAULT 0,
  successful_transactions integer DEFAULT 0,
  failed_transactions integer DEFAULT 0,
  refunded_transactions integer DEFAULT 0,
  gross_volume_fiat numeric DEFAULT 0,
  net_volume_fiat numeric DEFAULT 0,
  average_transaction_fiat numeric DEFAULT 0,
  okuru_fees_collected_fiat numeric DEFAULT 0,
  okuru_fees_collected_crypto jsonb DEFAULT '{}'::jsonb,
  crypto_volumes jsonb DEFAULT '{}'::jsonb,
  active_terminals integer DEFAULT 0,
  total_terminal_sessions integer DEFAULT 0,
  average_session_duration_minutes integer DEFAULT 0,
  active_staff_count integer DEFAULT 0,
  staff_transactions integer DEFAULT 0,
  total_wallet_addresses integer DEFAULT 0,
  verified_wallet_addresses integer DEFAULT 0,
  active_automations integer DEFAULT 0,
  automation_executions integer DEFAULT 0,
  automation_volume_fiat numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT okuru_merchant_analytics_pkey PRIMARY KEY (analytics_id),
  CONSTRAINT okuru_merchant_analytics_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.okuru_revenue_summary (
  summary_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  period_type character varying NOT NULL CHECK (period_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying, 'yearly'::character varying]::text[])),
  period_start date NOT NULL,
  period_end date NOT NULL,
  total_transactions_processed integer DEFAULT 0,
  total_gross_volume_fiat numeric DEFAULT 0,
  total_fees_collected_fiat numeric DEFAULT 0,
  average_fee_rate numeric DEFAULT 0.0100,
  btc_volume numeric DEFAULT 0,
  btc_fees_collected numeric DEFAULT 0,
  eth_volume numeric DEFAULT 0,
  eth_fees_collected numeric DEFAULT 0,
  usdc_volume numeric DEFAULT 0,
  usdc_fees_collected numeric DEFAULT 0,
  total_active_merchants integer DEFAULT 0,
  top_merchant_id uuid,
  top_merchant_volume numeric DEFAULT 0,
  is_finalized boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT okuru_revenue_summary_pkey PRIMARY KEY (summary_id),
  CONSTRAINT okuru_revenue_summary_top_merchant_id_fkey FOREIGN KEY (top_merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.pending_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  role text NOT NULL,
  merchant_id text,
  employee_id text,
  status text DEFAULT 'pending_invite'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  role_permissions jsonb DEFAULT '{}'::jsonb,
  pin_hash character varying,
  initiated_by uuid,
  initiated_by_name character varying,
  initiated_by_email character varying,
  approval_status character varying DEFAULT 'pending'::character varying CHECK (approval_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'denied'::character varying, 'expired'::character varying]::text[])),
  approved_by uuid,
  approved_by_name character varying,
  approved_by_email character varying,
  approved_at timestamp with time zone,
  denial_reason text,
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  merchant_id_uuid uuid,
  invitation_token character varying UNIQUE,
  invitation_sent_at timestamp with time zone,
  accepted_at timestamp with time zone,
  auth_user_id uuid,
  CONSTRAINT pending_users_pkey PRIMARY KEY (id),
  CONSTRAINT pending_users_initiated_by_fkey FOREIGN KEY (initiated_by) REFERENCES public.users(user_id),
  CONSTRAINT pending_users_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(user_id),
  CONSTRAINT pending_users_merchant_id_uuid_fkey FOREIGN KEY (merchant_id_uuid) REFERENCES public.merchants(merchant_id),
  CONSTRAINT pending_users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.product_import_logs (
  import_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  import_source character varying NOT NULL CHECK (import_source::text = ANY (ARRAY['csv'::character varying::text, 'square'::character varying::text, 'shopify'::character varying::text, 'clover'::character varying::text, 'toast'::character varying::text, 'lightspeed'::character varying::text])),
  file_name character varying,
  total_records integer DEFAULT 0,
  successful_imports integer DEFAULT 0,
  failed_imports integer DEFAULT 0,
  errors_log jsonb DEFAULT '[]'::jsonb,
  status character varying DEFAULT 'processing'::character varying CHECK (status::text = ANY (ARRAY['processing'::character varying::text, 'completed'::character varying::text, 'failed'::character varying::text, 'partial'::character varying::text])),
  imported_by uuid NOT NULL,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT product_import_logs_pkey PRIMARY KEY (import_id),
  CONSTRAINT product_import_logs_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT product_import_logs_imported_by_fkey FOREIGN KEY (imported_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.product_location_inventory (
  inventory_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  location_id uuid NOT NULL,
  merchant_id uuid NOT NULL,
  stock_quantity integer DEFAULT 0,
  low_stock_threshold integer DEFAULT 5,
  is_enabled boolean DEFAULT true,
  last_counted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_location_inventory_pkey PRIMARY KEY (inventory_id),
  CONSTRAINT product_location_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT product_location_inventory_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id),
  CONSTRAINT product_location_inventory_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.products (
  product_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  item_name character varying NOT NULL,
  variation_name character varying,
  sku character varying NOT NULL,
  description text,
  category character varying,
  price numeric NOT NULL,
  cost numeric,
  barcode character varying,
  weight numeric,
  dimensions jsonb,
  tax_name character varying,
  tax_rate numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  is_taxable boolean DEFAULT true,
  track_inventory boolean DEFAULT true,
  allow_backorders boolean DEFAULT false,
  image_url character varying,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  import_source character varying CHECK (import_source::text = ANY (ARRAY['manual'::character varying::text, 'csv'::character varying::text, 'square'::character varying::text, 'shopify'::character varying::text, 'clover'::character varying::text, 'toast'::character varying::text, 'lightspeed'::character varying::text])),
  external_id character varying,
  parent_product_id uuid,
  is_variation boolean DEFAULT false,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT products_pkey PRIMARY KEY (product_id),
  CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id),
  CONSTRAINT products_parent_product_id_fkey FOREIGN KEY (parent_product_id) REFERENCES public.products(product_id),
  CONSTRAINT products_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.report_exports (
  export_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  template_id uuid,
  schedule_id uuid,
  name character varying NOT NULL,
  export_type character varying NOT NULL CHECK (export_type::text = ANY (ARRAY['quick'::character varying::text, 'custom'::character varying::text, 'scheduled'::character varying::text, 'template'::character varying::text])),
  format character varying NOT NULL CHECK (format::text = ANY (ARRAY['csv'::character varying::text, 'xlsx'::character varying::text, 'json'::character varying::text, 'pdf'::character varying::text])),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'processing'::character varying::text, 'completed'::character varying::text, 'failed'::character varying::text, 'expired'::character varying::text])),
  filters jsonb DEFAULT '{}'::jsonb,
  columns jsonb DEFAULT '[]'::jsonb,
  record_count integer DEFAULT 0,
  file_size_kb integer,
  file_path text,
  download_count integer DEFAULT 0,
  error_message text,
  expires_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_downloaded_at timestamp with time zone,
  CONSTRAINT report_exports_pkey PRIMARY KEY (export_id),
  CONSTRAINT report_exports_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT report_exports_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.report_templates(template_id),
  CONSTRAINT report_exports_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.scheduled_reports(schedule_id),
  CONSTRAINT report_exports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.report_templates (
  template_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  name character varying NOT NULL,
  report_type character varying NOT NULL CHECK (report_type::text = ANY (ARRAY['transactions'::character varying::text, 'invoices'::character varying::text, 'revenue'::character varying::text, 'custom'::character varying::text])),
  filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  columns jsonb NOT NULL DEFAULT '[]'::jsonb,
  sorting jsonb DEFAULT '{"field": "created_at", "direction": "desc"}'::jsonb,
  grouping jsonb DEFAULT '{}'::jsonb,
  aggregations jsonb DEFAULT '[]'::jsonb,
  is_public boolean DEFAULT false,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT report_templates_pkey PRIMARY KEY (template_id),
  CONSTRAINT report_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id),
  CONSTRAINT report_templates_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.scheduled_reports (
  schedule_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  template_id uuid,
  name character varying NOT NULL,
  description text,
  schedule_type character varying NOT NULL CHECK (schedule_type::text = ANY (ARRAY['daily'::character varying::text, 'weekly'::character varying::text, 'monthly'::character varying::text, 'quarterly'::character varying::text])),
  schedule_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  export_format character varying DEFAULT 'csv'::character varying CHECK (export_format::text = ANY (ARRAY['csv'::character varying::text, 'xlsx'::character varying::text, 'json'::character varying::text, 'pdf'::character varying::text])),
  email_recipients jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  last_run_at timestamp with time zone,
  next_run_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scheduled_reports_pkey PRIMARY KEY (schedule_id),
  CONSTRAINT scheduled_reports_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT scheduled_reports_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.report_templates(template_id),
  CONSTRAINT scheduled_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.staff_permissions (
  permission_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  role_name character varying NOT NULL,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT staff_permissions_pkey PRIMARY KEY (permission_id),
  CONSTRAINT staff_permissions_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT staff_permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.standalone_invoice_timeline (
  event_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  invoice_id uuid NOT NULL,
  event_type character varying NOT NULL CHECK (event_type::text = ANY (ARRAY['created'::character varying, 'sent'::character varying, 'viewed'::character varying, 'payment_initiated'::character varying, 'payment_confirmed'::character varying, 'payment_failed'::character varying, 'expired'::character varying, 'cancelled'::character varying, 'refunded'::character varying, 'disputed'::character varying, 'reminder_sent'::character varying, 'updated'::character varying]::text[])),
  event_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT standalone_invoice_timeline_pkey PRIMARY KEY (event_id),
  CONSTRAINT standalone_invoice_timeline_invoice_fkey FOREIGN KEY (invoice_id) REFERENCES public.standalone_invoices(id),
  CONSTRAINT standalone_invoice_timeline_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.standalone_invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  invoice_number character varying NOT NULL UNIQUE,
  public_id character varying NOT NULL UNIQUE,
  merchant_id uuid NOT NULL,
  created_by uuid NOT NULL,
  title character varying,
  description text,
  notes text,
  customer_email character varying NOT NULL,
  customer_name character varying,
  customer_cc_emails ARRAY,
  billing_address jsonb,
  is_simple_amount boolean NOT NULL DEFAULT true,
  simple_amount numeric,
  line_items jsonb,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  discount_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  currency_mode character varying NOT NULL CHECK (currency_mode::text = ANY (ARRAY['fiat'::character varying, 'crypto'::character varying]::text[])),
  fiat_currency character varying,
  crypto_currency character varying,
  crypto_chain character varying,
  price_lock_secs integer NOT NULL DEFAULT 900,
  min_confirmations integer NOT NULL DEFAULT 1,
  allow_partial boolean NOT NULL DEFAULT false,
  tip_suggestions ARRAY DEFAULT ARRAY[0, 10, 15],
  tax_inclusive boolean NOT NULL DEFAULT false,
  settlement_wallet_id uuid,
  fee_payer character varying NOT NULL DEFAULT 'merchant'::character varying CHECK (fee_payer::text = ANY (ARRAY['merchant'::character varying, 'customer'::character varying]::text[])),
  terms_conditions text,
  refund_policy text,
  restricted_jurisdictions boolean NOT NULL DEFAULT false,
  kyc_threshold numeric,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'sent'::character varying, 'viewed'::character varying, 'partially_paid'::character varying, 'paid'::character varying, 'overpaid'::character varying, 'expired'::character varying, 'cancelled'::character varying, 'refunded'::character varying, 'disputed'::character varying]::text[])),
  payment_method character varying,
  payment_tx_hash character varying,
  payment_address character varying,
  amount_paid numeric,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  expires_at timestamp with time zone,
  due_date timestamp with time zone,
  tags jsonb DEFAULT '[]'::jsonb,
  webhook_url character varying,
  notification_email character varying,
  send_email boolean DEFAULT false,
  qr_code_data text,
  blockchain_tx_hash character varying,
  confirmation_count integer DEFAULT 0,
  settlement_status character varying DEFAULT 'pending'::character varying CHECK (settlement_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying]::text[])),
  settlement_tx_hash character varying,
  gas_fee_paid numeric,
  net_amount numeric,
  CONSTRAINT standalone_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT standalone_invoices_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT standalone_invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id),
  CONSTRAINT standalone_invoices_settlement_wallet_fkey FOREIGN KEY (settlement_wallet_id) REFERENCES public.merchant_wallets(wallet_id)
);
CREATE TABLE public.storefront_orders (
  order_id uuid NOT NULL DEFAULT gen_random_uuid(),
  storefront_id uuid NOT NULL,
  merchant_id uuid NOT NULL,
  product_id uuid NOT NULL,
  order_number character varying NOT NULL UNIQUE,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total_amount numeric NOT NULL,
  customer_email character varying,
  customer_name character varying,
  crypto_asset character varying NOT NULL,
  chain character varying DEFAULT 'BASE'::character varying,
  payment_address character varying,
  qr_code_data text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'failed'::character varying, 'refunded'::character varying, 'cancelled'::character varying, 'expired'::character varying]::text[])),
  blockchain_tx_hash character varying,
  confirmation_count integer DEFAULT 0,
  confirmed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT storefront_orders_pkey PRIMARY KEY (order_id),
  CONSTRAINT storefront_orders_storefront_id_fkey FOREIGN KEY (storefront_id) REFERENCES public.storefronts(storefront_id),
  CONSTRAINT storefront_orders_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT storefront_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.storefront_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  storefront_id uuid NOT NULL,
  product_id uuid NOT NULL,
  display_order integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  added_at timestamp with time zone DEFAULT now(),
  CONSTRAINT storefront_products_pkey PRIMARY KEY (id),
  CONSTRAINT storefront_products_storefront_id_fkey FOREIGN KEY (storefront_id) REFERENCES public.storefronts(storefront_id),
  CONSTRAINT storefront_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.storefronts (
  storefront_id uuid NOT NULL DEFAULT gen_random_uuid(),
  merchant_id uuid NOT NULL UNIQUE,
  created_by uuid NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  tagline character varying,
  theme character varying DEFAULT 'light'::character varying CHECK (theme::text = ANY (ARRAY['light'::character varying, 'dark'::character varying]::text[])),
  banner_url text,
  primary_color character varying DEFAULT '#3B82F6'::character varying,
  wallet_id uuid,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'published'::character varying, 'unpublished'::character varying]::text[])),
  published_at timestamp with time zone,
  unpublished_at timestamp with time zone,
  refund_policy text,
  terms text,
  social_links jsonb DEFAULT '{}'::jsonb,
  meta_title character varying,
  meta_description text,
  og_image_url text,
  allow_coupons boolean DEFAULT false,
  respect_inventory boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT storefronts_pkey PRIMARY KEY (storefront_id),
  CONSTRAINT storefronts_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT storefronts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id),
  CONSTRAINT storefronts_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.merchant_wallets(wallet_id)
);
CREATE TABLE public.tax_calculations (
  calculation_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transaction_id uuid,
  invoice_id uuid,
  merchant_id uuid NOT NULL,
  tax_setting_id uuid NOT NULL,
  base_amount numeric NOT NULL,
  tax_amount numeric NOT NULL,
  tax_rate numeric NOT NULL,
  calculation_method character varying DEFAULT 'percentage'::character varying CHECK (calculation_method::text = ANY (ARRAY['percentage'::character varying, 'fixed'::character varying, 'compound'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tax_calculations_pkey PRIMARY KEY (calculation_id),
  CONSTRAINT tax_calculations_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT tax_calculations_tax_setting_id_fkey FOREIGN KEY (tax_setting_id) REFERENCES public.tax_settings(tax_id),
  CONSTRAINT tax_calculations_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.tax_settings (
  tax_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  tax_name character varying NOT NULL DEFAULT 'Sales Tax'::character varying,
  tax_rate numeric NOT NULL DEFAULT 0.0000 CHECK (tax_rate >= 0::numeric AND tax_rate <= 1::numeric),
  is_enabled boolean DEFAULT false,
  auto_calculate boolean DEFAULT true,
  applies_to_products boolean DEFAULT true,
  applies_to_services boolean DEFAULT true,
  tax_jurisdiction character varying,
  tax_registration_number character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT tax_settings_pkey PRIMARY KEY (tax_id),
  CONSTRAINT tax_settings_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT tax_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.terminal_audit_log (
  audit_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  terminal_id uuid NOT NULL,
  merchant_id uuid NOT NULL,
  action character varying NOT NULL,
  actor_user_id uuid,
  actor_type character varying DEFAULT 'user'::character varying CHECK (actor_type::text = ANY (ARRAY['user'::character varying, 'system'::character varying, 'api'::character varying]::text[])),
  details jsonb,
  ip_address inet,
  user_agent text,
  timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT terminal_audit_log_pkey PRIMARY KEY (audit_id),
  CONSTRAINT terminal_audit_log_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id),
  CONSTRAINT terminal_audit_log_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT terminal_audit_log_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.terminal_configurations (
  config_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  terminal_id uuid NOT NULL,
  config_key character varying NOT NULL,
  config_value jsonb NOT NULL,
  config_type character varying DEFAULT 'setting'::character varying CHECK (config_type::text = ANY (ARRAY['setting'::character varying, 'ui'::character varying, 'security'::character varying, 'payment'::character varying]::text[])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT terminal_configurations_pkey PRIMARY KEY (config_id),
  CONSTRAINT terminal_configurations_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id)
);
CREATE TABLE public.terminal_crypto_config (
  config_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  terminal_id uuid NOT NULL UNIQUE,
  merchant_id uuid NOT NULL,
  crypto_1 character varying NOT NULL,
  crypto_1_blockchain character varying NOT NULL,
  crypto_1_enabled boolean DEFAULT true,
  crypto_1_min_amount numeric DEFAULT 0.00001,
  crypto_1_max_amount numeric DEFAULT 1000000,
  crypto_2 character varying NOT NULL,
  crypto_2_blockchain character varying NOT NULL,
  crypto_2_enabled boolean DEFAULT true,
  crypto_2_min_amount numeric DEFAULT 0.001,
  crypto_2_max_amount numeric DEFAULT 1000000,
  crypto_3 character varying NOT NULL,
  crypto_3_blockchain character varying NOT NULL,
  crypto_3_enabled boolean DEFAULT true,
  crypto_3_min_amount numeric DEFAULT 1.0,
  crypto_3_max_amount numeric DEFAULT 1000000,
  configured_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT terminal_crypto_config_pkey PRIMARY KEY (config_id),
  CONSTRAINT terminal_crypto_config_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id),
  CONSTRAINT terminal_crypto_config_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT terminal_crypto_config_configured_by_fkey FOREIGN KEY (configured_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.terminal_permissions (
  permission_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  terminal_id uuid NOT NULL,
  user_id uuid NOT NULL,
  merchant_id uuid NOT NULL,
  can_process_payments boolean DEFAULT true,
  can_issue_refunds boolean DEFAULT false,
  can_view_reports boolean DEFAULT false,
  can_manage_inventory boolean DEFAULT false,
  allowed_start_time time without time zone,
  allowed_end_time time without time zone,
  allowed_days ARRAY,
  is_active boolean DEFAULT true,
  granted_by uuid,
  granted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT terminal_permissions_pkey PRIMARY KEY (permission_id),
  CONSTRAINT terminal_permissions_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id),
  CONSTRAINT terminal_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT terminal_permissions_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT terminal_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.terminal_sessions (
  session_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  terminal_id uuid NOT NULL,
  user_id uuid NOT NULL,
  merchant_id uuid NOT NULL,
  started_at timestamp with time zone DEFAULT now(),
  last_activity timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '08:00:00'::interval),
  ended_at timestamp with time zone,
  auth_method character varying DEFAULT 'pin'::character varying CHECK (auth_method::text = ANY (ARRAY['pin'::character varying, 'badge'::character varying, 'biometric'::character varying]::text[])),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'expired'::character varying, 'ended'::character varying, 'locked'::character varying]::text[])),
  login_ip inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT terminal_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT terminal_sessions_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id),
  CONSTRAINT terminal_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT terminal_sessions_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.terminal_transaction_events (
  event_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transaction_id uuid NOT NULL,
  terminal_id uuid NOT NULL,
  merchant_id uuid NOT NULL,
  event_type character varying NOT NULL CHECK (event_type::text = ANY (ARRAY['transaction_initiated'::character varying, 'payment_received'::character varying, 'confirmation_pending'::character varying, 'transaction_confirmed'::character varying, 'transaction_failed'::character varying, 'refund_initiated'::character varying, 'refund_completed'::character varying, 'automation_triggered'::character varying]::text[])),
  event_data jsonb,
  dashboard_synced boolean DEFAULT false,
  webhook_sent boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT terminal_transaction_events_pkey PRIMARY KEY (event_id),
  CONSTRAINT terminal_transaction_events_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id),
  CONSTRAINT terminal_transaction_events_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id),
  CONSTRAINT terminal_transaction_events_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.terminals (
  terminal_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  location_id uuid,
  name character varying NOT NULL,
  pairing_code character varying UNIQUE,
  status character varying DEFAULT 'offline'::character varying CHECK (status::text = ANY (ARRAY['pending_activation'::character varying::text, 'active'::character varying::text, 'online'::character varying::text, 'offline'::character varying::text, 'maintenance'::character varying::text, 'suspended'::character varying::text, 'paired'::character varying::text])),
  firmware_version character varying,
  ip_address inet,
  last_heartbeat timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  api_key character varying UNIQUE,
  blockchain_registered boolean DEFAULT false,
  registration_tx character varying,
  device_type character varying DEFAULT 'physical'::character varying CHECK (device_type::text = ANY (ARRAY['physical'::character varying, 'virtual'::character varying]::text[])),
  hardware_info jsonb,
  last_seen timestamp with time zone,
  paired_at timestamp with time zone,
  CONSTRAINT terminals_pkey PRIMARY KEY (terminal_id),
  CONSTRAINT terminals_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT terminals_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id)
);
CREATE TABLE public.transactions (
  transaction_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  location_id uuid,
  terminal_id uuid,
  staff_user_id uuid,
  amount_fiat numeric NOT NULL,
  fiat_currency character varying NOT NULL,
  amount_crypto numeric NOT NULL,
  crypto_currency character varying NOT NULL,
  blockchain character varying NOT NULL,
  tx_hash character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  confirmations integer DEFAULT 0,
  required_confirmations integer DEFAULT 1,
  fee numeric,
  tip numeric,
  notes text,
  automation_triggered boolean DEFAULT false,
  automation_type character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  terminal_session_id uuid,
  processed_by_user_id uuid,
  customer_receipt_sent boolean DEFAULT false,
  merchant_notification_sent boolean DEFAULT false,
  dashboard_updated_at timestamp with time zone,
  okuru_fee_rate numeric DEFAULT 0.0100,
  okuru_fee_fiat numeric,
  okuru_fee_crypto numeric,
  okuru_fee_collected boolean DEFAULT false,
  okuru_fee_collected_at timestamp with time zone,
  merchant_net_amount_fiat numeric,
  merchant_net_amount_crypto numeric,
  token_address character varying,
  receiver_address character varying,
  chain_id integer NOT NULL,
  transaction_type character varying DEFAULT 'PH Terminal'::character varying CHECK (transaction_type::text = ANY (ARRAY['VT Terminal'::character varying, 'PH Terminal'::character varying, 'Invoice'::character varying]::text[])),
  CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id),
  CONSTRAINT transactions_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT transactions_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(location_id),
  CONSTRAINT transactions_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id),
  CONSTRAINT transactions_staff_user_id_fkey FOREIGN KEY (staff_user_id) REFERENCES public.users(user_id),
  CONSTRAINT transactions_terminal_session_id_fkey FOREIGN KEY (terminal_session_id) REFERENCES public.terminal_sessions(session_id),
  CONSTRAINT transactions_processed_by_user_id_fkey FOREIGN KEY (processed_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.tx_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  invoice_id uuid,
  chain_id integer NOT NULL,
  tx_hash character varying NOT NULL,
  block_number bigint NOT NULL,
  log_index integer NOT NULL,
  event_type character varying NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying, 'orphaned'::character varying, 'reorged'::character varying]::text[])),
  confirmations integer DEFAULT 0,
  details jsonb,
  occurred_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tx_events_pkey PRIMARY KEY (id),
  CONSTRAINT tx_events_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.user_preferences (
  preference_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  theme character varying DEFAULT 'system'::character varying CHECK (theme::text = ANY (ARRAY['light'::character varying, 'dark'::character varying, 'system'::character varying]::text[])),
  language character varying DEFAULT 'English'::character varying,
  timezone character varying DEFAULT 'America/New_York'::character varying,
  notification_email boolean DEFAULT true,
  notification_push boolean DEFAULT true,
  notification_sms boolean DEFAULT false,
  notification_transaction_alerts boolean DEFAULT true,
  notification_security_alerts boolean DEFAULT true,
  notification_marketing_updates boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_preferences_pkey PRIMARY KEY (preference_id),
  CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.users (
  user_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  name character varying NOT NULL,
  email character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['admin'::character varying::text, 'merchant'::character varying::text, 'merchant_admin'::character varying::text, 'staff'::character varying::text, 'okuru_admin'::character varying::text])),
  employee_id character varying,
  pin_hash character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  approved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  auth_user_id uuid UNIQUE,
  temp_password_hash character varying,
  temp_password_expires_at timestamp without time zone,
  password_change_required boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT users_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.virtual_terminal_passwords (
  password_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  salt character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  failed_attempts integer DEFAULT 0,
  locked_until timestamp with time zone,
  CONSTRAINT virtual_terminal_passwords_pkey PRIMARY KEY (password_id),
  CONSTRAINT virtual_terminal_passwords_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id)
);
CREATE TABLE public.virtual_terminal_rate_limits (
  rate_limit_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ip_address inet NOT NULL UNIQUE,
  failed_attempts integer DEFAULT 0,
  last_attempt_at timestamp with time zone DEFAULT now(),
  blocked_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT virtual_terminal_rate_limits_pkey PRIMARY KEY (rate_limit_id)
);
CREATE TABLE public.virtual_terminal_settings_audit (
  audit_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  merchant_id uuid NOT NULL,
  changed_by uuid,
  old_enabled boolean,
  new_enabled boolean,
  change_reason text,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT virtual_terminal_settings_audit_pkey PRIMARY KEY (audit_id),
  CONSTRAINT virtual_terminal_settings_audit_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchants(merchant_id),
  CONSTRAINT virtual_terminal_settings_audit_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.wallet_addresses (
  address_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  wallet_id uuid NOT NULL,
  blockchain character varying NOT NULL,
  address character varying NOT NULL,
  is_verified boolean DEFAULT false,
  verification_signature text,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  terminal_id uuid,
  merchant_id uuid,
  CONSTRAINT wallet_addresses_pkey PRIMARY KEY (address_id),
  CONSTRAINT wallet_addresses_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.merchant_wallets(wallet_id),
  CONSTRAINT wallet_addresses_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.terminals(terminal_id)
);